title: 3BluePulse Capstone Design
page-top-title: 3BluePulse
top-section-bg-text: Mechanical Engineering
home-subtitle: 3BluePulse&ensp;|&ensp;by 秦祯欣、闫冠旭、殷悦
home-subtitle-2: Cullen College of Engineering, University of Houston
copyright-text: '&copy; ZhenxinQin 2025-2026. All Rights Reserved.'
